baseurl: ''
exclude: ['README.md', vendor]
permalink: pretty
title: 'PATh'
url: "https://path-cc.io"
key: path

google_analytics_id: G-0CCSDQV212
homepage:
  show_alert: true
  show_call_box: true
logo: '/images/logo/Logo_Round_Med.png'
footer:
  copyright_text: 'This project is supported by National Science Foundation under Cooperative Agreement OAC-2030508. Any opinions, findings, conclusions or recommendations expressed in this material are those of the authors and do not necessarily reflect the views of the National Science Foundation.'

# Jekyll does not build hidden directories by default.
include:
  - .well-known
  - .nojekyll

seo:
  meta_og_title: "Partnership to Advance Throughput Computing"
  meta_og_type: "website"
  meta_og_url: "https://path-cc.io"
  meta_og_description: "PATh brings together the Center for High Throughput Computing and the Open Science Grid in order to advance the nation’s campuses and science communities through the use of distributed High Throughput Computing."
  meta_og_image: "https://path-cc.io/images/logo/Logo_Primary_Acronym.png"
  meta_twitter_card: "summary"
  meta_twitter_site: "PATh"
  meta_twitter_image: "images/logo/Logo_Round_Med.png"

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  news:
    output: true
    permalink: /news/:path/
  events_legacy:
    output: true
    permalink: /events/:path/
  events:
    output: true
    permalink: /events/:year/:month/:day/:title/
  gil:
    output: true
    permalink: /GIL/:path/
  docs:
    output: true
    permalink: /facility/docs/:path/
  facility:
    output: true
    permalink: /facility/:title.html
  articles:
    output: true
    permalink: /news/:path/
  redirects:
    output: true
    permalink: /:path

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      type: news
    values:
      layout: news
      bodyClass: page-news-single
  - scope:
      type: articles
    values:
      layout: news
      bodyClass: page-news-single
  - scope:
      type: events_legacy
    values:
      layout: events
  - scope:
      type: events
    values:
      layout: events_modern
  - scope:
      path: 'images'
    values:
      image: true
  - scope:
      type: docs
    values:
      layout: table-of-contents
  - scope:
      type: redirects
    values:
      layout: redirect



sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap
  - jekyll-seo-tag
